### PR TITLE
Allows load_dot_env to parse empty .env

### LINKED ISSUE #5: Should `load_dot_env` fail when .env is empty?
Should `load_dot_env` fail when .env is empty?

```r
library(dotenv)
# Load from a file
tmp <- tempfile()
cat("", file = tmp)
load_dot_env(tmp)
#> Error in (function (...) : all arguments must be named
```

I can send a PR to fix this if you think this is an odd behaviour.

### PR DESCRIPTION
**Pull request by cimentadaj**
Should close #5. Let me know if this make sense, otherwise I can adapt.

### CODE REVIEW

**Comment by cimentadaj** [comment]
Just a reminder @gaborcsardi  in case you didn't see this. Just to confirm.

**Comment by gaborcsardi** [comment]
Thanks much!

**Comment by cimentadaj** [comment]
Of course! Any estimation on when this could arrive on CRAN?

**Comment by gaborcsardi** [comment]
The plan is tomorrow.

**Comment by gaborcsardi** [comment]
It is on CRAN now.

**Pull request merged**
